version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.18.4

jobs:
  install-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: '.'
          paths:
            - node_modules

  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: Lint
          command: yarn lint

  prettier-check:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: Check prettier
          command: npx prettier --check .

  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: Run tests
          command: yarn test

  test-e2e:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: Run e2e tests
          command: yarn test:e2e

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies

      - lint:
          requires:
            - install-dependencies

      - prettier-check:
          requires:
            - install-dependencies

      - test:
          requires:
            - install-dependencies

      - test-e2e:
          requires:
            - install-dependencies
